# GitHub Pages configuration for Svenska IPSC Ranking
title: Svenska IPSC Ranking
description: Rankingsystem för svenska IPSC-skyttar baserat på OpenSkill-algoritm
url: https://ipsc-ranking.com
baseurl: /

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Include data files
include:
  - data

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: sv
author: Jonas Emilsson

# Social links
github_username: jemilsson